### ISSUE TITLE
Satellite REST server not starting on Pi

### ISSUE THREAD

**Issue by kylegibbons** [bitfocus/companion-satellite#106]
I have downloaded the Satellite .img file and flashed it on an RPI 4

I updated Satellite to ensure I had the latest version.

In the config file, REST_PORT is set to 9999 as is the default.

When I check the systemctl status for the Satellite I am seeing the message "REST server not starting: port 0".

I have also configured the host and port in the config file for my Companion instance. 

The Satellite with a StreamDeck attached is also not showing up in Companion (I have a Windows Satellite that is showing up correctly).

I see no messages in the log about trying to connect to companion, so I am suspecting it is not reading the config file for some reason. Any help would be greatly appreciated.

**Comment by Julusian** [comment]
There was an issue with some images recently, due to recent raspbian changing where the boot partition is mounted.
I suspect that is what you were observing, the result of which was you having two config files, with you modifying one and it reading the other.

The config files and paths have been reworked as part of adding a web interface, so hopefully this will work better in later releases
