### ISSUE TITLE
Docker hotplug usb (fixed)

### ISSUE THREAD

**Issue by adamflorizone** [bitfocus/companion-satellite#129]
Is docker hot pluging usb not working for docker rootless? 

Was docker ever finished?

I ended up rewriting the docker files to get hot plug usb to work for docker rootless:
https://github.com/adamflorizone/companion-satellite

I can open PR but I need to know the broken status of the docker files.

**Comment by Julusian** [comment]
From what I remember, I think the current image did work but as you can gather from reading it, it felt incredibly brittle due to rebuilding `usb` and `node-hid`.
Both of those libraries didn't work properly due to their reliance on `udev` which refuses to run in docker.

I don't remember if I fixed this part, but at some point while `usb` would detect new devices, `node-hid` would not see them and so would be unable to open them.

All of this and the lack of user demand for a working docker image led me to abandon the effort.

**Comment by Julusian** [comment]
I'm going to close this, as it looks like while you have something working, you are battling the same problems with hotplug I was.
Your approach to handling usb events is one solution to that, but confirms that usb in docker is painful and inconsistent, so isn't something I am keen to support for now

------

Copying the key portion of what you have done here, as a future reference for myself in case I change my mind
```
# Run this as container root:
{
    while true; do
        ln -sf /dev/hostdev/hidraw* /dev
        inotifywait -e create /dev/hostdev 2>/dev/null |
        while read -r directory event filename; do
            echo inotifywait: "${directory} ${event} ${filename}"
            ln -sf "${directory}/${filename}" /dev

            if [[ "$filename" == hidraw* ]]; then
                # This is a quick hack for non udev docker!
                echo restarting node... node /app/satellite/dist/main.js
                pkill --full "node /app/satellite/dist/main.js"
            fi 
        done
    done
} &
```
