### ISSUE TITLE
Update Development instructions

### ISSUE THREAD

**Issue by sparks-alec** [bitfocus/companion-satellite#149]
Working on #138 on a fork and struggling to get my development environment set up correctly. Currently on macOS Apple Silicon.

These are the places where readme.md seems to be outdated:
- Use Node 20 as v1.9.0 calls
- Rebuild using `yarn rebuild` not `yarn electron-rebuild`
- Run using `yarn dev:electron` not `yarn dev-electron`

Additionally, many files I have not touched will not lint. It's unclear to me which files are supposed to lint and which ones are not- this error from VS Code suggests a mismatch between ESLint config and TS config. My ESLint plugin is v3.0.10.

```
Parsing error: ESLint was configured to run on `<tsconfigRootDir>/satellite/src/client.ts` using `parserOptions.project`: <tsconfigRootDir>/tsconfig.json
However, that TSConfig does not include this file. Either:
- Change ESLint's list of included files to not include this file
- Change that TSConfig to include this file
- Create a new TSConfig that includes this file and include it in your parserOptions.project
See the typescript-eslint docs for more info: https://typescript-eslint.io/troubleshooting/typed-linting#i-get-errors-telling-me-eslint-was-configured-to-run--however-that-tsconfig-does-not--none-of-those-tsconfigs-include-this-file
```

Is there any other setup steps necessary? Plugins or local settings to apply? I have totally wiped my VS Code plugin settings so I do not think my local configuration is the issue.

**Comment by Julusian** [comment]
I have updated the readme with those suggestions.

I didn't notice those eslint errors because my vscode hadn't updated itself since installing back in february :facepalm: , and was too old for the plugin to work.
But the real 'error' was that the vscode plugin does not automatically understand mono-repos, and was getting confused when not finding an eslint config at the root of the repository. I've added that config now
