### ISSUE TITLE
"internal: set surface with index to page" not working

### ISSUE THREAD

**Issue by Tilltv** [bitfocus/companion-satellite#62]
Hi,
the internal function "set surface with index to page" doesn't work for me. If I use "set surface with s/n to page" there are no problems.
(Direct connection via USB also works)

Am I doing something wrong or is there a bug?

Companion Version: 2.4.1 (2.4.1+4898-v2-4.1-9646192a)
Satellite Version: 1.3.1

**Comment by Julusian** [comment]
Sorry for not checking this sooner, but I am unable to reproduce this (in 3.0) and don't see how it could happen for just satellite devices. If there is a bug it would be on the companion side rather than here.

Im going to assume this has stopped being a problem, but if you are able to reproduce it in 3.0, let me know and if you could provide a page config export and a screenshot of the surfaces list that might give some insight on what is happening
