### ISSUE TITLE
Cant install Companion Satellite headless on linux

### ISSUE THREAD

**Issue by alex-Arc** [bitfocus/companion-satellite#76]
running 
```curl https://raw.githubusercontent.com/bitfocus/companion-satellite/master/pi-image/install.sh | sh```
produces this warning
```
warning Pattern ["node-hid@npm:@julusian/hid@2.5.0-3","node-hid@^2.1.1","node-hid@^2.1.1","node-hid@^2.1.1"] is trying to unpack in the same destination "/usr/local/share/.cache/yarn/v6/npm-node-hid-2.5.0-3-4d0a1aabef8a47b79a3ccdb30fc5b53e8618f5e1-integrity/node_modules/node-hid" as pattern ["node-hid@npm:@julusian/hid@2.5.0-3"]. This could result in non-deterministic behavior, skipping.
```

and then when systemctl tries to run it this error appears
```
Started Bitfocus Companion Satellite.
node:internal/modules/cjs/loader:1338
Aug 05 20:40:54 node[10751]:   return process.dlopen(module, path.toNamespacedPath(filename));
Aug 05 20:40:54 node[10751]:                  ^
Aug 05 20:40:54 node[10751]: Error: libfontconfig.so.1: cannot open shared object file: No such file or directo>
Aug 05 20:40:54 node[10751]:     at Module._extensions..node (node:internal/modules/cjs/loader:1338:18)
Aug 05 20:40:54 node[10751]:     at Module.load (node:internal/modules/cjs/loader:1117:32)
Aug 05 20:40:54 node[10751]:     at Module._load (node:internal/modules/cjs/loader:958:12)
Aug 05 20:40:54 node[10751]:     at Module.require (node:internal/modules/cjs/loader:1141:19)
Aug 05 20:40:54 node[10751]:     at require (node:internal/modules/cjs/helpers:110:18)
Aug 05 20:40:54 node[10751]:     at Object.<anonymous> (/usr/local/src/companion-satellite/node_modules/@julusi>
Aug 05 20:40:54 node[10751]:     at Module._compile (node:internal/modules/cjs/loader:1254:14)
Aug 05 20:40:54 node[10751]:     at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
Aug 05 20:40:54 node[10751]:     at Module.load (node:internal/modules/cjs/loader:1117:32)
Aug 05 20:40:54 node[10751]:     at Module._load (node:internal/modules/cjs/loader:958:12) {
Aug 05 20:40:54 node[10751]:   code: 'ERR_DLOPEN_FAILED'
Aug 05 20:40:54 rocpis node[10751]: }
```

#67 somewhat matches
but this is on a fresh install using the new method

**Comment by Julusian** [comment]
The warning is normal and can be ignored. The error in the second block needs attention.
What image/distro are you using here? It is missing a system library that we depend upon. I can update the script to install the dependency, but there could be more than just the one which are missing, so it would be good to test it myself

**Comment by alex-Arc** [comment]
OK
it is running on https://wiki.radxa.com/RockpiS using there Ubuntu image
is there a way for me to generate that list for you

**Comment by alex-Arc** [comment]
Ah just found that the error message was cut off
it is the `skia-canvas` that is failing

```
Aug 06 19:58:10 node[595]: Node.js v18.16.0
Aug 06 19:58:10 systemd[1]: satellite.service: Main process exited, code=exited, status=1/FAILURE
Aug 06 19:58:10 systemd[1]: satellite.service: Failed with result 'exit-code'.
Aug 06 19:58:11 systemd[1]: satellite.service: Scheduled restart job, restart counter is at 3.
Aug 06 19:58:11 systemd[1]: Stopped Bitfocus Companion Satellite.
Aug 06 19:58:11 systemd[1]: Started Bitfocus Companion Satellite.
Aug 06 19:58:13 node[606]: node:internal/modules/cjs/loader:1338
Aug 06 19:58:13 node[606]:   return process.dlopen(module, path.toNamespacedPath(filename));
Aug 06 19:58:13 node[606]:                  ^
Aug 06 19:58:13 node[606]: Error: libfontconfig.so.1: cannot open shared object file: No such file or directory
Aug 06 19:58:13 node[606]:     at Module._extensions..node (node:internal/modules/cjs/loader:1338:18)
Aug 06 19:58:13 node[606]:     at Module.load (node:internal/modules/cjs/loader:1117:32)
Aug 06 19:58:13 node[606]:     at Module._load (node:internal/modules/cjs/loader:958:12)
Aug 06 19:58:13 node[606]:     at Module.require (node:internal/modules/cjs/loader:1141:19)
Aug 06 19:58:13 node[606]:     at require (node:internal/modules/cjs/helpers:110:18)
Aug 06 19:58:13 node[606]:     at Object.<anonymous> (/usr/local/src/companion-satellite/node_modules/@julusian/skia-canvas/lib/index.js:23:29)
Aug 06 19:58:13 node[606]:     at Module._compile (node:internal/modules/cjs/loader:1254:14)
Aug 06 19:58:13 node[606]:     at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
Aug 06 19:58:13 node[606]:     at Module.load (node:internal/modules/cjs/loader:1117:32)
Aug 06 19:58:13 node[606]:     at Module._load (node:internal/modules/cjs/loader:958:12) {
Aug 06 19:58:13 node[606]:   code: 'ERR_DLOPEN_FAILED'
Aug 06 19:58:13 node[606]: }
```

**Comment by alex-Arc** [comment]
found that `libfontconfig1` should be installed if a ‘slim’ image is used 
I now get to
```
Aug 06 20:18:07 systemd[1]: Started Bitfocus Companion Satellite.
Aug 06 20:18:10 node[4888]: Starting
Aug 06 20:18:10 node[4888]: adding new device: /dev/hidraw0
Aug 06 20:18:10 node[4888]: existing = []
Aug 06 20:18:10 node[4888]: Registering key events for AL25J2C06040
Aug 06 20:18:11 node[4888]: Connecting to xxx.xxx.xxx:16622
```

**Comment by Julusian** [comment]
Doing a `sudo apt install libfontconfig1` should also fix it on the other image. If that is the only one needed I can add it to the script, but I suspect it could then fail on another missing library.

Yeah, I was expecting this to be caused by skia-canva. its the only thing that has changed here recently

**Comment by alex-Arc** [comment]
That was it 
including it by default wold be nice :)

**Comment by Keksstar** [comment]
`root@rockpis:/home/rock# curl https://raw.githubusercontent.com/bitfocus/companion-satellite/master/pi-image/install.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1865  100  1865    0     0   6365      0 --:--:-- --:--:-- --:--:--  6343
This will attempt to install Companion Satellite as a system service on this device.
It is designed to be run on headless servers, but can be used on desktop machines if you are happy to not have the tray icon.
A user called 'satellite' will be created to run the service, and various scripts will be installed to manage the service
Adding user `satellite' ...
Adding new group `satellite' (1001) ...
Adding new user `satellite' (1001) with group `satellite' ...
Creating home directory `/home/satellite' ...
Copying files from `/etc/skel' ...
Hit:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease
Hit:2 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease
Hit:3 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease
Hit:4 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease
Get:5 http://apt.radxa.com/focal-stable focal InRelease [2359 B]
Err:5 http://apt.radxa.com/focal-stable focal InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 9B98116C9AA302C7
Reading package lists... Done
W: GPG error: http://apt.radxa.com/focal-stable focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 9B98116C9AA302C7
E: The repository 'http://apt.radxa.com/focal-stable focal InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
`

That´s my installation progress on an RockPiS. The Streamdeck isn´t showing the Companion Logo. I assume the Satellite isn´t running at all.
Does does look right? If not, how to fix it?

**Comment by Keksstar** [comment]
Solved with all of this...

```
sudo apt-get update && upgrade
sudo apt-get install -y wget
sudo apt-get install -y curl
sudo apt-get install -y libfontconfig1
sudo apt-get install -y tzdata
sudo apt-get install -y nano

export DISTRO=buster-stable
wget -O - apt.radxa.com/$DISTRO/public.key | sudo apt-key add -
sudo apt-get update

sudo sysctl net.ipv6.conf.all.disable_ipv6=1

sudo apt install nodejs
sudo apt install npm

sudo su

curl https://raw.githubusercontent.com/bitfocus/companion-satellite/master/pi-image/install.sh | sh
```

**Comment by Julusian** [comment]
@Keksstar I suspect that the lines
```
export DISTRO=buster-stable
wget -O - apt.radxa.com/$DISTRO/public.key | sudo apt-key add -
sudo apt-get update
```
are the relevent thing here. Which suggests that the image you used is 'broken' in that it did not have apt setup correctly.

Maybe some of:
```
sudo apt-get install -y tzdata
sudo apt-get install -y nano
```
were needed too, depending on whether they were included in the image already.

These lines will not be needed, we bring and manager our own version of nodejs
```
sudo apt install nodejs
sudo apt install npm
```
