### ISSUE TITLE
Edit config on custom install?

### ISSUE THREAD

**Issue by Keksstar** [bitfocus/companion-satellite#89]
Hi,
I´ve installed the satellite on an RockPi Ubuntu.
How can I edit the config to give the satellite the Companion address?
What´s the satellite user password?

Thanks!

**Comment by Keksstar** [comment]
Worked after this....

`sudo apt-get update && upgrade
sudo apt-get install -y wget
sudo apt-get install -y curl
sudo apt-get install -y libfontconfig1
sudo apt-get install -y tzdata
sudo apt-get install -y nano

export DISTRO=buster-stable
wget -O - apt.radxa.com/$DISTRO/public.key | sudo apt-key add -
sudo apt-get update

sudo sysctl net.ipv6.conf.all.disable_ipv6=1

sudo apt install nodejs
sudo apt install npm

sudo su

curl https://raw.githubusercontent.com/bitfocus/companion-satellite/master/pi-image/install.sh | sh`

**Comment by Julusian** [comment]
> How can I edit the config to give the satellite the Companion address?

It is designed so that the config file is on the fat32 sd card partition, so that it is editable from another machine.  
I don't know if the image you used has this partition.

> What´s the satellite user password?

The satellite user isnt intended to be logged into. Instead you should login with the default user account, after setting that up (if necessary for your image)
